name: .NET Core Simple Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        dotnet-version: [6.0, 8.0]

    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore and Build
      run: |
        dotnet restore ICT3101_Calculator.sln
        dotnet build ICT3101_Calculator.sln --configuration Release --no-restore

    - name: Test with build (NUnit)
      run: dotnet test ICT3101_Calculator.UnitTests/ICT3101_Calculator.UnitTests.csproj --configuration Release --verbosity normal

    - name: Test with build (SpecFlow)
      run: dotnet test SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj --configuration Release --verbosity normal