name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./SubFolderThatContainsSolutionFile  # Specify your solution's folder if it's not in the root

    env:
      Solution_Name: ICT3101_Calculator.sln  # Your solution file
      NUnit_Test_Project_Path: Tests/ICT3101_Calculator.UnitTests/ICT3101_Calculator.UnitTests.csproj  # Adjust path if needed
      SpecFlow_Test_Project_Path: Tests/SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj  # Adjust path if needed

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Run NUnit tests
    - name: Run NUnit Tests
      working-directory: ./Tests/ICT3101_Calculator.UnitTests  # Ensure the correct relative path
      run: dotnet test --no-build --verbosity normal

    # Run SpecFlow tests
    - name: Run SpecFlow Tests
      working-directory: ./Tests/SpecFlowCalculatorTests  # Ensure the correct relative path
      run: dotnet test --no-build --verbosity normal


