name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        dotnet-version: [6.0, 8.0]  # Matrix for both .NET 6 and .NET 8

    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./  # Assuming the solution and tests are in the root folder

    env:
      Solution_Name: ICT3101_Calculator.sln
      NUnit_Test_Project_Path: ICT3101_Calculator.UnitTests/ICT3101_Calculator.UnitTests.csproj
      SpecFlow_Test_Project_Path: SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}  # Use matrix variable for version

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Run NUnit tests
    - name: Run NUnit Tests
      working-directory: ./ICT3101_Calculator.UnitTests
      run: dotnet test --no-build --verbosity normal

    # Run SpecFlow tests
    - name: Run SpecFlow Tests
      working-directory: ./SpecFlowCalculatorTests
      run: dotnet test --no-build --verbosity normal

