name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./SubFolderThatContainsSolutionFile  # Correct if solution file is in subfolder

    env:
      Solution_Name: ICT3101_Calculator.sln
      NUnit_Test_Project_Path: Tests/ICT3101_Calculator.UnitTests/ICT3101_Calculator.UnitTests.csproj
      SpecFlow_Test_Project_Path: Tests/SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Run NUnit tests
    - name: Run NUnit Tests
      working-directory: .ICT3101_Calculator.UnitTests  # Fix path here
      run: dotnet test --no-build --verbosity normal

    # Run SpecFlow tests
    - name: Run SpecFlow Tests
      working-directory: ./SpecFlowCalculatorTests  # Fix path here
      run: dotnet test --no-build --verbosity normal

