name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30  # Prevent hanging builds

    defaults:
      run:
        working-directory: ./

    env:
      Solution_Name: ICT3101_Calculator.sln
      NUnit_Test_Project_Path: ICT3101_Calculator.UnitTests/ICT3101_Calculator.UnitTests.csproj
      SpecFlow_Test_Project_Path: SpecFlowCalculatorTests/SpecFlowCalculatorTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }} --verbosity minimal

    # Build the solution
    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore --verbosity minimal

    # Run NUnit tests
    - name: Run NUnit Tests
      working-directory: ./ICT3101_Calculator.UnitTests
      run: dotnet test --verbosity normal --configuration Release --framework net8.0

    # Run SpecFlow tests
    - name: Run SpecFlow Tests
      working-directory: ./SpecFlowCalculatorTests
      run: dotnet test --verbosity normal --configuration Release --framework net8.0

    



